directories:
  output: installer-output
  buildResources: build
appId: com.crmmarmeria.app
productName: CRM Marmeria
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    target: portable
    arch:
      - x64
  artifactName: CRM-Marmeria-Installer-${version}.exe
electronVersion: 28.3.3
